### ISSUE TITLE
warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]

### ISSUE THREAD

**Issue by xiaolaba** [BojanJurca/Esp32_web_ftp_telnet_server_template#18]
hi, seeing compiler warning like this,

warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
               cronTabAdd ("0 0 0 1 1 * newYear'sGreetingsToProgrammer");  // triggers at the beginning of each year

`             cronTabAdd ( "* * * * * * gotTime");  // triggers only once - when ESP32 reads time from NTP servers for the first time
              cronTabAdd ( "0 0 0 1 1 * newYear'sGreetingsToProgrammer");  // triggers at the beginning of each year
              cronTabAdd ( "0 * * * * * onMinute");  // triggers each minute at 0 seconds
`

change to (char *), this will remove those warning,
`             cronTabAdd ((char *) "* * * * * * gotTime");  // triggers only once - when ESP32 reads time from NTP servers for the first time
              cronTabAdd ((char *) "0 0 0 1 1 * newYear'sGreetingsToProgrammer");  // triggers at the beginning of each year
              cronTabAdd ((char *) "0 * * * * * onMinute");  // triggers each minute at 0 seconds
`

**Comment by BojanJurca** [comment]
Thank you for letting me know.

I have corrected the .ino file.
