### ISSUE TITLE
Are there any plans to implement mime types for web servers?

### ISSUE THREAD

**Issue by tomoyan596** [BojanJurca/Esp32_web_ftp_telnet_server_template#6]
Hello 😊

It's not a problem, but png, jpg, mp4 ... all are Content-Type: text / html ;.
![757C9A92-BD45-47FC-B977-E14C9A94843B](https://user-images.githubusercontent.com/3541130/109374244-2b153f00-78f7-11eb-908d-7c22d5787b29.jpeg)
It is useful to have a mime-types.h definition.

Thank you for the wonderful template 🙇

**Comment by BojanJurca** [comment]
Thank you for your feedback. I'll keep it in mind for the next release which will happen, well, when I have time. 

Meanwhile you can use a workaround by adding the following code (or something similar) into httpRequestHandler function:

String httpRequestHandler (String& httpRequest, httpServer::wwwSessionParameters *wsp) { // - has to be reentrant!

  if (httpRequest.indexOf (".png ") >= 0)       wsp->setHttpResponseHeaderField ("Content-Type", "image/png");
  else if (httpRequest.indexOf (".html ") >= 0) wsp->setHttpResponseHeaderField ("Content-Type", "text/html");
  else                                          wsp->setHttpResponseHeaderField ("Content-Type", "text/plain");
  // ...

You can also put it into httpServer.__internalHttpRequestHandler__ function instead if it is more convenient for you.

**Comment by BojanJurca** [comment]
Please download latest webSererver.hpp file and replace the one you have.

**Comment by tomoyan596** [comment]
Hello 😃
Thank you for your prompt reply.

As you said, you don't have to access the URL directly in your browser, so add it to each webServer.hpp if needed 😊

Thank you very much 🙇‍♂️
