### ISSUE TITLE
ESP32 stream function is working conditionally with different browser

### ISSUE THREAD

**Issue by xiaolaba** [BojanJurca/Esp32_web_ftp_telnet_server_template#9]
hi, ESP32 stream function is working conditionally with different browser
Firefox is not working, Win10 Edge ok, Android chrome ok, any idea whether server side issue or the browser variance ?

![revised_index](https://user-images.githubusercontent.com/2533993/109587201-9ce0c900-7b41-11eb-9d92-ee609d8b0d0a.JPG)

here is screen shot with win10 machine, on the left EDGE is ok, on the right firefox used was ver 86. 32 bit, error? 
![firefox_NG_Edge_OK](https://user-images.githubusercontent.com/2533993/109587207-9f432300-7b41-11eb-9c07-4f7130afb476.JPG)

**Comment by BojanJurca** [comment]
Please download the latest webServer.hpp file and replace the one you already have. Firefox should work now.

**Comment by xiaolaba** [comment]
head up and salute.
yes, it works.
